#server:
#  port: 6002
#  servlet:
#    session:
#      timeout: 24h
#
#spring:
#  application:
#    name: crm-excontract
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.0.2.55:8848
#  datasource:
#    url: jdbc:mysql://10.0.8.28:3306/sefonoa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: rootroot
#
#  quartz:
#    jobStoreType: MEMORY
#  jackson:
#    time-zone: GMT+8
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
#logging:
#  level:
#    com.sefonsoft.oa.dao: debug
#
#
#reportDayLastHours: 10
#
#Approver:
#  per: crm:workreport:daily:list