#server:
#  port: 9527
#
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.0.2.55:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          # 路由了http://localhost:9001/payment/get+某某的所有接口只要用
#          # http://localhost:9527/payment/get/1001就能访问，隐蔽了微服务的端口
#      routes:
#        #        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#        #          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#        #          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#        #          predicates:
#        #            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#
#        - id: crm-excontract_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://crm-excontract #匹配后提供服务的路由地址
#        - id: crm-excontract_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://crm-main #匹配后提供服务的路由地址
#          #断言，相当于一个筛选器
#          predicates:
##            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#            #            - After=2020-03-21T15:51:37.485+08:00[Asia/Shanghai]
#            #            - Cookie=username,zzyy
#            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#
##被nacos代替
##eureka:
##  instance:
##    hostname: cloud-gateway-service
##  client: #服务提供者provider注册进eureka服务列表内
##    service-url:
##      register-with-eureka: true
##      fetch-registry: true
##      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
